// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProviderInbox.Service.Infrastructure;

#nullable disable

namespace ProviderInbox.Service.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260118123000_InitialCreate")]
public partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.9");
        modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("ProviderInbox.Domain.InboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
            b.Property<bool>("ActionRequired").HasColumnType("bit");
            b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("DueAt").HasColumnType("datetimeoffset");
            b.Property<string>("Npi").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<string>("OfficeNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<bool>("Pinned").HasColumnType("bit");
            b.Property<int>("Priority").HasColumnType("int");
            b.Property<DateTimeOffset?>("ReadAt").HasColumnType("datetimeoffset");
            b.Property<string>("ReferenceId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<byte[]>("RowVersion").IsRowVersion().HasColumnType("rowversion");
            b.Property<int?>("SlaHours").HasColumnType("int");
            b.Property<string>("Summary").HasMaxLength(400).HasColumnType("nvarchar(400)");
            b.Property<int>("Status").HasColumnType("int");
            b.Property<string>("Title").IsRequired().HasMaxLength(180).HasColumnType("nvarchar(180)");
            b.Property<int>("Type").HasColumnType("int");
            b.Property<DateTimeOffset?>("SnoozedUntil").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");

            b.HasKey("Id");

            b.HasIndex("Npi", "OfficeNumber", "Pinned", "Priority", "Status", "DueAt", "UpdatedAt")
                .HasDatabaseName("IX_InboxMessages_Npi_OfficeNumber_Pinned_Priority_Status_DueAt_UpdatedAt");

            b.HasIndex("Npi", "OfficeNumber", "Type", "CreatedAt")
                .HasDatabaseName("IX_InboxMessages_Npi_OfficeNumber_Type_CreatedAt");

            b.ToTable("InboxMessages");
        });
#pragma warning restore 612, 618
    }
}
